// mockCommsData.js - Real-world Company Communication Channels & Preloaded Commitments

export const PRELOADED_COMMS = [
  {
    id: "comm-slack-1",
    channelType: "slack",
    channelName: "#product-launch",
    channelIcon: "💬",
    title: "Slack: Q3 Launch Coordination Thread",
    timestamp: "Today, 10:42 AM",
    sender: "Aarav Sharma (Head of Product)",
    senderAvatar: "👨‍💼",
    rawContent: `Aarav: Team, we need to lock down our deliverables for the enterprise beta release next week.\nRahul: Got it. Rahul, please send the sales report by Friday 5 PM so we can review Q2 conversion rates.\nPriya: On it! I will complete the Figma design tokens and Dark Mode specs tomorrow before noon.\nVikram: Can you check with the AWS supplier about the GPU quota increase by Wednesday?\nAarav: Sounds good. I'll review the draft customer contracts by Thursday morning.\nNeha: Just checking in, did anyone order lunch? (General banter)\nRahul: Yes, ordered pizza already haha.`,
    detectedCommitments: [
      {
        id: "com-101",
        taskTitle: "Send Q2 sales conversion report to product team",
        owner: "Rahul Verma",
        ownerAvatar: "👨‍💻",
        ownerRole: "Sales Lead",
        requester: "Aarav Sharma",
        deadline: "Friday, 5:00 PM",
        deadlineISO: "2026-08-28T17:00:00",
        priority: "High",
        confidence: 96,
        sourceType: "Slack",
        sourceChannel: "#product-launch",
        originalSnippet: "Rahul, please send the sales report by Friday 5 PM so we can review Q2 conversion rates.",
        status: "pending", // "pending", "confirmed", "dismissed"
        urgencyDays: 3
      },
      {
        id: "com-102",
        taskTitle: "Complete Figma design tokens and Dark Mode specifications",
        owner: "Priya Patel",
        ownerAvatar: "👩‍🎨",
        ownerRole: "Senior UI/UX Designer",
        requester: "Self-committed",
        deadline: "Tomorrow, 12:00 PM",
        deadlineISO: "2026-08-26T12:00:00",
        priority: "Urgent",
        confidence: 94,
        sourceType: "Slack",
        sourceChannel: "#product-launch",
        originalSnippet: "I will complete the Figma design tokens and Dark Mode specs tomorrow before noon.",
        status: "pending",
        urgencyDays: 1
      },
      {
        id: "com-103",
        taskTitle: "Check with AWS supplier regarding GPU instance quota increase",
        owner: "Vikram Malhotra",
        ownerAvatar: "👨‍🔧",
        ownerRole: "DevOps Engineer",
        requester: "Aarav Sharma",
        deadline: "Wednesday, 6:00 PM",
        deadlineISO: "2026-08-26T18:00:00",
        priority: "High",
        confidence: 91,
        sourceType: "Slack",
        sourceChannel: "#product-launch",
        originalSnippet: "Can you check with the AWS supplier about the GPU quota increase by Wednesday?",
        status: "pending",
        urgencyDays: 1
      },
      {
        id: "com-104",
        taskTitle: "Review draft customer enterprise contracts",
        owner: "Aarav Sharma",
        ownerAvatar: "👨‍💼",
        ownerRole: "Head of Product",
        requester: "Self-committed",
        deadline: "Thursday, 10:00 AM",
        deadlineISO: "2026-08-27T10:00:00",
        priority: "Medium",
        confidence: 88,
        sourceType: "Slack",
        sourceChannel: "#product-launch",
        originalSnippet: "I'll review the draft customer contracts by Thursday morning.",
        status: "pending",
        urgencyDays: 2
      }
    ]
  },
  {
    id: "comm-email-1",
    channelType: "email",
    channelName: "Inbox: Client Escalation",
    channelIcon: "✉️",
    title: "Email Thread: Apex Financial Cloud Migration SLA",
    timestamp: "Yesterday, 4:15 PM",
    sender: "Sarah Jenkins (Apex Financial - VP Tech)",
    senderAvatar: "👩‍💼",
    rawContent: `From: Sarah Jenkins <sjenkins@apexfin.com>\nTo: dev-leads@company.com\nSubject: Re: Production Database Migration Timeline\n\nHi Team,\nWe need confirmation on the database failover SLA before signing the MSA.\nCould someone from backend please provide the updated RPO/RTO benchmark document by tomorrow EOD?\nAlso, please update the staging environment with sanitized data by Thursday.\n\nBest regards,\nSarah`,
    detectedCommitments: [
      {
        id: "com-105",
        taskTitle: "Provide updated RPO/RTO benchmark document to Apex Financial",
        owner: "Marcus Vance",
        ownerAvatar: "👨‍💻",
        ownerRole: "Backend Lead",
        requester: "Sarah Jenkins (Client)",
        deadline: "Tomorrow EOD (6:00 PM)",
        deadlineISO: "2026-08-26T18:00:00",
        priority: "Urgent",
        confidence: 98,
        sourceType: "Email",
        sourceChannel: "Client: Apex Financial",
        originalSnippet: "Could someone from backend please provide the updated RPO/RTO benchmark document by tomorrow EOD?",
        status: "pending",
        urgencyDays: 1
      },
      {
        id: "com-106",
        taskTitle: "Update staging environment with sanitized data",
        owner: "Elena Rostova",
        ownerAvatar: "👩‍🚀",
        ownerRole: "SRE / Database Admin",
        requester: "Sarah Jenkins (Client)",
        deadline: "Thursday, 5:00 PM",
        deadlineISO: "2026-08-27T17:00:00",
        priority: "Medium",
        confidence: 92,
        sourceType: "Email",
        sourceChannel: "Client: Apex Financial",
        originalSnippet: "Also, please update the staging environment with sanitized data by Thursday.",
        status: "pending",
        urgencyDays: 2
      }
    ]
  },
  {
    id: "comm-meeting-1",
    channelType: "meeting",
    channelName: "Zoom: Sprint 14 Architecture Review",
    channelIcon: "🎙️",
    title: "Meeting Transcript: Multi-Region Failover Architecture",
    timestamp: "Today, 11:30 AM",
    sender: "Alex Rivera (Engineering Director)",
    senderAvatar: "👨‍🔬",
    rawContent: `Alex: Alright team, let's wrap up our sprint architecture decisions.\nDavid: I will take full responsibility for writing the API deprecation changelog by Monday morning.\nAlex: Perfect. Elena, please configure the ArgoCD automated rollouts before our Friday deploy freeze.\nElena: Agreed, I'll have the canary metrics tested by Thursday afternoon.\nAlex: Thanks everyone, great meeting. Let's execute.`,
    detectedCommitments: [
      {
        id: "com-107",
        taskTitle: "Write and publish REST API deprecation changelog",
        owner: "David Kim",
        ownerAvatar: "👔",
        ownerRole: "Product Manager",
        requester: "Self-committed",
        deadline: "Monday, 10:00 AM",
        deadlineISO: "2026-08-31T10:00:00",
        priority: "Medium",
        confidence: 95,
        sourceType: "Meeting",
        sourceChannel: "Zoom: Architecture Review",
        originalSnippet: "I will take full responsibility for writing the API deprecation changelog by Monday morning.",
        status: "pending",
        urgencyDays: 6
      },
      {
        id: "com-108",
        taskTitle: "Configure ArgoCD automated rollouts and canary metrics before freeze",
        owner: "Elena Rostova",
        ownerAvatar: "👩‍🚀",
        ownerRole: "SRE Lead",
        requester: "Alex Rivera",
        deadline: "Thursday, 3:00 PM",
        deadlineISO: "2026-08-27T15:00:00",
        priority: "High",
        confidence: 97,
        sourceType: "Meeting",
        sourceChannel: "Zoom: Architecture Review",
        originalSnippet: "Elena, please configure the ArgoCD automated rollouts before our Friday deploy freeze.",
        status: "pending",
        urgencyDays: 2
      }
    ]
  }
];

export const INITIAL_CONFIRMED_TASKS = [
  {
    id: "TASK-201",
    title: "Send Q2 sales conversion report to product team",
    owner: "Rahul Verma",
    ownerAvatar: "👨‍💻",
    ownerRole: "Sales Lead",
    requester: "Aarav Sharma",
    deadline: "Friday, 5:00 PM",
    deadlineISO: "2026-08-28T17:00:00",
    priority: "High",
    status: "in-progress", // "todo", "in-progress", "waiting", "done"
    sourceType: "Slack",
    sourceChannel: "#product-launch",
    originalSnippet: "Rahul, please send the sales report by Friday 5 PM so we can review Q2 conversion rates.",
    confidence: 96,
    confirmedAt: "2026-08-25 10:45 AM",
    isForgottenRisk: true, // Triggers the "Forgotten-Work Warning" if due today or approaching
    notes: "Pulled initial numbers from Salesforce; finalizing CSV export with growth team."
  },
  {
    id: "TASK-202",
    title: "Deliver high-fidelity Figma design tokens for Dark Mode",
    owner: "Priya Patel",
    ownerAvatar: "👩‍🎨",
    ownerRole: "Senior UI/UX Designer",
    requester: "Self-committed",
    deadline: "Today, 5:00 PM",
    deadlineISO: "2026-08-25T17:00:00",
    priority: "Urgent",
    status: "todo",
    sourceType: "Slack",
    sourceChannel: "#product-launch",
    originalSnippet: "I will complete the Figma design tokens and Dark Mode specs tomorrow before noon.",
    confidence: 94,
    confirmedAt: "2026-08-25 09:30 AM",
    isForgottenRisk: true,
    notes: "Tokens ready in Figma; need to export JSON for frontend team."
  },
  {
    id: "TASK-203",
    title: "Review draft customer enterprise contracts with Legal",
    owner: "Aarav Sharma",
    ownerAvatar: "👨‍💼",
    ownerRole: "Head of Product",
    requester: "Self-committed",
    deadline: "Thursday, 10:00 AM",
    deadlineISO: "2026-08-27T10:00:00",
    priority: "Medium",
    status: "waiting",
    sourceType: "Slack",
    sourceChannel: "#product-launch",
    originalSnippet: "I'll review the draft customer contracts by Thursday morning.",
    confidence: 88,
    confirmedAt: "2026-08-24 03:15 PM",
    isForgottenRisk: false,
    notes: "Waiting on General Counsel legal redlines."
  },
  {
    id: "TASK-204",
    title: "Provide updated RPO/RTO benchmark document to Apex Financial",
    owner: "Marcus Vance",
    ownerAvatar: "👨‍💻",
    ownerRole: "Backend Lead",
    requester: "Sarah Jenkins (Client)",
    deadline: "Yesterday (Overdue)",
    deadlineISO: "2026-08-24T18:00:00",
    priority: "Urgent",
    status: "in-progress",
    sourceType: "Email",
    sourceChannel: "Client: Apex Financial",
    originalSnippet: "Could someone from backend please provide the updated RPO/RTO benchmark document by tomorrow EOD?",
    confidence: 98,
    confirmedAt: "2026-08-23 04:30 PM",
    isForgottenRisk: true,
    notes: "⚠️ OVERDUE: Customer waiting for executive sign-off."
  },
  {
    id: "TASK-205",
    title: "Audit AWS KMS encryption keys rotation across prod volumes",
    owner: "Tariq Mansoor",
    ownerAvatar: "🕵️",
    ownerRole: "SecOps Lead",
    requester: "Security Steering",
    deadline: "Aug 22, 2026",
    deadlineISO: "2026-08-22T17:00:00",
    priority: "High",
    status: "done",
    sourceType: "Meeting",
    sourceChannel: "Security Sync",
    originalSnippet: "Tariq will rotate all production KMS master keys by Friday.",
    confidence: 97,
    confirmedAt: "2026-08-20 11:00 AM",
    isForgottenRisk: false,
    notes: "Completed and audited in AWS CloudTrail."
  }
];

export const TEAM_MEMBERS = [
  { id: "tm-1", name: "Rahul Verma", role: "Sales Lead", avatar: "👨‍💻", department: "Sales", activeTasks: 3, reliabilityScore: 92 },
  { id: "tm-2", name: "Priya Patel", role: "UI/UX Lead", avatar: "👩‍🎨", department: "Design", activeTasks: 2, reliabilityScore: 97 },
  { id: "tm-3", name: "Aarav Sharma", role: "Head of Product", avatar: "👨‍💼", department: "Product", activeTasks: 4, reliabilityScore: 95 },
  { id: "tm-4", name: "Marcus Vance", role: "Backend Engineer", avatar: "👨‍🔧", department: "Engineering", activeTasks: 3, reliabilityScore: 89 },
  { id: "tm-5", name: "Elena Rostova", role: "DevOps & SRE", avatar: "👩‍🚀", department: "Infrastructure", activeTasks: 2, reliabilityScore: 98 },
  { id: "tm-6", name: "Vikram Malhotra", role: "Cloud Architect", avatar: "👨‍🔬", department: "Engineering", activeTasks: 2, reliabilityScore: 94 }
];
